import { Redirect, type Href } from "expo-router";

/**
 * Compatibility redirect: the legacy `/profile` deep link resolves to the
 * Account screen at `/(app)/account`. This file sits OUTSIDE the tab group
 * on purpose — route groups are URL-transparent, so the deep link keeps
 * working while tab discovery sees only the real tabs.
 */
export default function LegacyProfileRedirect() {
	// Typed routes are generated by Metro; until the next dev run picks up the
	// new `/account` route, widen to Href so the redirect still typechecks.
	return <Redirect href={"/(app)/account" as Href} />;
}
