import { Redirect, type Href } from 'expo-router';

/**
 * Legacy settings deep link. Account controls now live on the Account screen
 * opened by the profile avatar, so /settings points there.
 */
export default function LegacySettingsRedirect() {
	// Typed routes are generated by Metro; until the next dev run picks up the
	// new `/account` route, widen to Href so the redirect still typechecks.
	return <Redirect href={"/(app)/account" as Href} />;
}
