packages:
  - 'packages/*'
allowBuilds:
  esbuild: true
  msgpackr-extract: true
  sharp: true
  unrs-resolver: false
onlyBuiltDependencies:
  - esbuild
  - unrs-resolver
patchedDependencies:
  '@expo/metro-runtime@6.1.2': patches/@expo__metro-runtime@6.1.2.patch
  expo-router: patches/expo-router.patch
