import { useRouter, type Href } from "expo-router";
import { useCallback } from "react";
import { Pressable, StyleSheet, View } from "react-native";

import { ThemedText } from "@/components/themed-text";
import { useSession } from "@/features/session/session-context";
import { useThemeColor } from "@/hooks/use-theme-color";

/**
 * Consistent entry to the Account screen from Story, Together, Plans, and
 * Ours. Shows the signed-in user's initial. Account is a pushed screen over
 * the tabs, so opening it keeps the tab bar in the hierarchy behind it.
 */
export function SpaceAvatarButton() {
	const router = useRouter();
	const { user } = useSession();
	const borderStrong = useThemeColor({}, "borderStrong");
	const surface2 = useThemeColor({}, "surface2");
	const textPrimary = useThemeColor({}, "textPrimary");

	const rawName = user?.displayName?.trim() || user?.email?.trim() || "?";
	const initial = rawName.charAt(0).toUpperCase();

	const handlePress = useCallback(() => {
		// Typed routes are generated by Metro; until the next dev run picks up
		// the new `/account` route, widen to Href so the push still typechecks.
		router.push("/(app)/account" as Href);
	}, [router]);

	return (
		<Pressable
			accessibilityLabel="Account and settings"
			accessibilityHint="Opens your account, relationship, and app settings"
			accessibilityRole="button"
			onPress={handlePress}
			style={styles.touchTarget}
		>
			<View
				style={[
					styles.avatar,
					{ borderColor: borderStrong, backgroundColor: surface2 },
				]}
			>
				<ThemedText type="body" style={{ color: textPrimary }}>
					{initial}
				</ThemedText>
			</View>
		</Pressable>
	);
}

const styles = StyleSheet.create({
	touchTarget: {
		width: 44,
		height: 44,
		alignItems: "center",
		justifyContent: "center",
	},
	avatar: {
		width: 36,
		height: 36,
		borderRadius: 18,
		borderWidth: StyleSheet.hairlineWidth,
		alignItems: "center",
		justifyContent: "center",
	},
});
